### ISSUE TITLE
Croebh's Checklist for Alias Stuff

### ISSUE THREAD

**Issue by Croebh** [otfbm/issues#19]
This is a list of the features I'm currently planning on implementing to `!map`, in no specific order. This list is far from exhaustive.

 - [x] Replace `spellbook` tags with arg requirements
 - Before - `Abi-Dalzim’s Horrid Wilting - squaretop,30,00C177,{aim}`
 - After  - `Abi-Dalzim’s Horrid Wilting - Requires -aim` (Not final)
 - [x] Add `maplist` tags with what it contains
 - Before - `Forest`
 - After  - `Forest - Background, 20x24, Walls` (Not final)
 - [ ] Refactor order of code blocks in order to reduce chance things are missed
 - Make sure we check for `-t` target first before anything else, possibly define it off the hop
 - Make sure `-mapattach` is checked *before* changing options
 - [x] Make the alias auto `-mapattach` if there are certain named combatants
 - `DM`, `Map`, `Lair`, etc
 - Possibly try to check for `!i add` combatants (I think if `combatant.hp` is None, they're `!i add`?)
 - Hopefully reduce confusion as to why settings weren't saved
 - [x] Add support for multiple `-t` targets
 - Possibly `-t "OR1|-move B3"` format? unsure, highly requested
 - [x] Add in support for objects
 - Confer with Nerds with this, as they've already completed a proof of concept
 - [x] Refactor the help screens
 - Confer with LP on this, as they have a lot more experience in this, and have already started on it
 - [ ] General refactor of code using more consistent standards
 - I'm pretty sure I currently use like 4 different methods to do the same thing in different places
 - Generalizing it would make it easier to maintain and add on to
 - [x] Refactor the `-savemap` or whatever it is settings from being a list to a dict
 - This would allow saving a background, size, view, description, walls, objects etc 
 - Current system allows BG, BG and Size, BG Size and View, Walls, and View, with walls and view being under a different command?

**Comment by nerdsanddragons** [comment]
-savemap should probably be the command that saves everything. mapbg, mapsize, mapoptions, walls and objects, into a variable like {mapLayer}

**Comment by nerdsanddragons** [comment]
- [ ] Add 'F' in map options for alternative font.

**Comment by Croebh** [comment]
You can check that one off :p i did it quickly

**Comment by Croebh** [comment]
- [ ] Possibly add support for `!map A3`, which would function the same as `!move A3`, removing the need for a second alias?

**Comment by nerdsanddragons** [comment]
I completely agree with the idea. Bring everything back under the main alias

**Comment by nerdsanddragons** [comment]
- [ ] Add the ability to easily move overlays
• Maybe something like !map -t <target> -overaim <location> Or -overtarg <targ>

**Comment by nerdsanddragons** [comment]
You can check off a couple of those items up there on your list croebh after you merge my PR I sent you. 

Couple ideas/to do’s I’m thinking about..

- [x] Add the ability to save current map state with all combatant notes so it can be called up later. 
• Maybe -savebattle will save and -loadbattle to call it
•Maybe have the save also save all the -mapattach info as well so -loadbattle loads everything. (User would have to add all the enemies first into initiative before running -loadbattle)

**Comment by BardicPerspiration** [comment]
Suggestion: add shortened forms of all commands beginning with -map, e.g. -attach, -size, -view, -options.
