### ISSUE TITLE
Docs Updates

### ISSUE THREAD

**Issue by digitalsadhu** [otfbm/issues#8]
**Describe the bug**

Docs are now out of date and need the following added:

## Tokens

- Creating a shortcode by sending a request to `https://token.otfbm.io/meta/<base64 of full URL>`
- Passing shortcodes to a token segment `/d3-Urzer~<shortcode>`

## Change to door definition format when drawing walls

- `-d` door
- `-b` double door
- `-s` secret door
- `-o` open door

E.g.
http://localhost:4001/_B2G2G4H4-dH6G6G8-sF9E10-bC10B10B2_B6-oG6

## TODO

- [x] doors
- [x] tokens (this is a biggie)
- [x] arrow overlays
- [x] grid transparency as a percentage
- [x] disable border opacity option
- [ ] Image size limits lifted (explain what the deal is now)
- [x] panning around the map with the `c4:d3` syntax and the `b3:10x10` syntax
- [ ] color support added to walls and doors
- [ ] ~ flag added to disable facial recognition on tokens

**Comment by Croebh** [comment]
Arrow overlays are missing

**Comment by Ydomat** [comment]
need to add color pink as well

**Comment by Ydomat** [comment]
https://github.com/otfbm/docs/commit/f2f10f900bb7e31fa1273747c4fed8fba4509775

Added color Pink
Added verbiage for token images
Added border ppacity 
Added map pan features
Updated grid transparency
Removed image size requirement
Added arrow overlay

**Comment by digitalsadhu** [comment]
@Ydomat I've updated checklists and added 1 new.

**Comment by Ydomat** [comment]
I'll do these updates this by friday. busy week.

**Comment by Ydomat** [comment]
https://github.com/otfbm/docs/commit/5cff81a93503b0585f4b5fee720aa95e6b93620f

Updated Sidebar for "Alias" Guides
Added facial recognition on token
Added labels for tokens with images
added wall and door colors.

**Comment by Ydomat** [comment]
Assuming these changes look good. let's close this issue and open a new one so new updates have a clean slate.

**Comment by Ydomat** [comment]
CLosing this as updates complete.
